[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
bincode = "1.3.3"
byteorder = "1.4.3"
dotenv = "0.15.0"
lazy_static = "1.4.0"
shared = { path = "../shared" }
