[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
async-std = "1.12.0"
bincode = "1.3.3"
byteorder = "1.4.3"
serde = { version = "1.0.163", features = ["derive"] }
